name: Deploy to Github Pages

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    container:
      image: roboticsmicrofarms/plant-3d-vision:latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install -r requirements.txt

    - run: mkdocs build

    - name: Deploy if master branch
      if: github.ref == 'refs/heads/master'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./site
